plugin.bootstrap_package.settings.scss.primary: '#213E6D'
plugin.bootstrap_package.settings.scss.secondary: '#4890F9'
plugin.bootstrap_package.settings.scss.tertiary: '#F6F9FF'
plugin.bootstrap_package.settings.scss.quaternary: '#F1F1E6'
plugin.bootstrap_package.settings.scss.link-color: '$secondary'
plugin.bootstrap_package.view.layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/'
plugin.bootstrap_package.view.partialRootPath: 'EXT:bca13/Resources/Private/Partials/'
plugin.bootstrap_package.view.templateRootPath: 'EXT:bca13/Resources/Private/Templates/'

plugin.bootstrap_package_contentelements.view.layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/ContentElements/'
plugin.bootstrap_package_contentelements.view.partialRootPath: 'EXT:bca13/Resources/Private/Partials/ContentElements/'
plugin.bootstrap_package_contentelements.view.templateRootPath: 'EXT:bca13/Resources/Private/Templates/ContentElements/'

page.logo.file: 'EXT:bca13/Resources/Public/Images/bca-192x192.png'
page.logo.fileInverted: 'EXT:bca13/Resources/Public/Images/bca-192x192.png'
page.logo.width: 210
page.logo.alt: 'bca13'
page.logo.linktitle: 'bca13'

page.favicon.file: 'EXT:bca13/Resources/Public/Icons/favicon.ico'

page.fluidtemplate.layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/Page/'
page.fluidtemplate.partialRootPath: 'EXT:bca13/Resources/Private/Partials/Page/'
page.fluidtemplate.templateRootPath: 'EXT:bca13/Resources/Private/Templates/Page/'
