plugin:
  bootstrap_package:
    settings:
      scss:
        primary: '#213e6d'
        secondary: '#013859'
    view:
      layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/'
      partialRootPath: 'EXT:bca13/Resources/Private/Partials/'
      templateRootPath: 'EXT:bca13/Resources/Private/Templates/'
  bootstrap_package_contentelements:
    view:
      layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/ContentElements/'
      partialRootPath: 'EXT:bca13/Resources/Private/Partials/ContentElements/'
      templateRootPath: 'EXT:bca13/Resources/Private/Templates/ContentElements/'
page:
  logo:
    file: 'EXT:bca13/Resources/Public/Images/bca-192x192.png'
    fileInverted: 'EXT:bca13/Resources/Public/Images/bca-192x192.png'
    width: 210
    alt: 'BCA'
    linktitle: 'BCA'
  favicon:
    file: 'EXT:bca13/Resources/Public/Icons/favicon.ico'
  fluidtemplate:
    layoutRootPath: 'EXT:bca13/Resources/Private/Layouts/Page/'
    partialRootPath: 'EXT:bca13/Resources/Private/Partials/Page/'
    templateRootPath: 'EXT:bca13/Resources/Private/Templates/Page/'
